# Generated by Django 2.1.15 on 2020-10-15 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import idea.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_num', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='5', max_length=10)),
                ('member_name1', models.CharField(max_length=30)),
                ('school_name1', models.CharField(max_length=50)),
                ('department_name1', models.CharField(max_length=30)),
                ('department_grade1', models.CharField(max_length=10)),
                ('phone_number1', models.CharField(max_length=20)),
                ('email_addr1', models.EmailField(blank=True, max_length=254)),
                ('member_name2', models.CharField(blank=True, max_length=30)),
                ('school_name2', models.CharField(blank=True, max_length=50)),
                ('department_name2', models.CharField(blank=True, max_length=30)),
                ('department_grade2', models.CharField(blank=True, max_length=10)),
                ('phone_number2', models.CharField(blank=True, max_length=20)),
                ('email_addr2', models.EmailField(blank=True, max_length=254)),
                ('member_name3', models.CharField(blank=True, max_length=30)),
                ('school_name3', models.CharField(blank=True, max_length=50)),
                ('department_name3', models.CharField(blank=True, max_length=30)),
                ('department_grade3', models.CharField(blank=True, max_length=10)),
                ('phone_number3', models.CharField(blank=True, max_length=20)),
                ('email_addr3', models.EmailField(blank=True, max_length=254)),
                ('member_name4', models.CharField(blank=True, max_length=30)),
                ('school_name4', models.CharField(blank=True, max_length=50)),
                ('department_name4', models.CharField(blank=True, max_length=30)),
                ('department_grade4', models.CharField(blank=True, max_length=10)),
                ('phone_number4', models.CharField(blank=True, max_length=20)),
                ('email_addr4', models.EmailField(blank=True, max_length=254)),
                ('member_name5', models.CharField(blank=True, max_length=30)),
                ('school_name5', models.CharField(blank=True, max_length=50)),
                ('department_name5', models.CharField(blank=True, max_length=30)),
                ('department_grade5', models.CharField(blank=True, max_length=10)),
                ('phone_number5', models.CharField(blank=True, max_length=20)),
                ('email_addr5', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=40, unique=True)),
                ('team_topic', models.CharField(max_length=50)),
                ('team_school', models.CharField(max_length=40)),
                ('team_teacher', models.CharField(max_length=30)),
                ('video_link', models.URLField(blank=True)),
                ('code_link', models.URLField(blank=True)),
                ('readme', models.FileField(blank=True, upload_to=idea.models.user_readme_path)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=50)),
                ('department_name', models.CharField(max_length=30)),
                ('department_grade', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_addr', models.EmailField(max_length=254)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.FloatField(default=0)),
                ('score2', models.FloatField(default=0)),
                ('score3', models.FloatField(default=0)),
                ('judge_user', models.FloatField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Team')),
            ],
        ),
        migrations.AddField(
            model_name='membertemp',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.Team'),
        ),
    ]
